CREATE TABLE [dbo].[Orders]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
    [IdUser] UNIQUEIDENTIFIER NOT NULL,
	[OrderDate] DATE NOT NULL,
	[OrderStatus] NVARCHAR(50) NOT NULL,
	[CreatedDate] DATE NOT NULL,
	[LastModifiedDate] DATE NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(IdUser) REFERENCES AspNetUsers(Id)
)